name: stag_env
channels:
  - conda-forge
  - defaults
dependencies:
  # 基础环境：3.14
  - python=3.14
  - pip
  - libgcc-ng
  - libstdcxx-ng
  
  # 核心计算库
  # 服务器是 CUDA 12.8

  # 数据处理与病理影像库
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - openslide
  
  - pip:
      # 补全你提到的关键工具
      - tifffile  # 用于处理病理 Mask 的 TIFF 文件
      - openslide-python    # 处理 WSI 图像的核心
      
      # 项目核心：STAG-Unet 相关
      # 染色标准化
      # 空间注意力与图像变换
      # 医疗影像增强
      
      # 训练监控与辅助
      - tensorboard
      - tqdm
      - scipy